
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { useState, useEffect } from 'react';

const MeetingNotesSimulation = () => {
  const [step, setStep] = useState(0); // 0: Zoom, 1: Transcript, 2: Summary

  const transcript = [
    "[09:00] Alice: Welcome everyone to our weekly sync. Let's start with project Alpha updates.",
    "[09:02] Bob: Alpha is on track. We've completed module A, and module B development is 50% done.",
    "[09:05] Carol: Great work, Bob! For marketing, we're planning a campaign launch for Alpha next month. Need final content by end of next week.",
    "[09:07] Alice: Understood, Carol. Bob, can you confirm content delivery by Friday?",
    "[09:08] Bob: Yes, I'll ensure content for the marketing campaign is ready by Friday EOD.",
    "[09:10] Alice: Perfect. Let's move to Project Beta. Any updates, David?",
    "[09:12] David: Beta is facing a slight delay with external vendor integration. We anticipate a 3-day setback.",
    "[09:15] Alice: Okay, David. Please send out a risk assessment and mitigation plan by tomorrow.",
  ];

  const summary = [
    "**Meeting Summary:**",
    "This week's sync focused on Project Alpha and Beta. Project Alpha is on track, with Module B 50% complete. The marketing campaign for Alpha is scheduled for next month, with content due by end of next week.",
    "Project Beta is experiencing a 3-day delay due to vendor integration issues.",
    "",
    "**Action Items:**",
    "- **Bob:** Confirm and deliver marketing campaign content for Project Alpha by Friday EOD.",
    "- **David:** Send out a risk assessment and mitigation plan for Project Beta by tomorrow.",
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.05, delayChildren: 0.5 } },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  };

  useEffect(() => {
    if (step === 0) {
      // Simulate Zoom download
      const timer = setTimeout(() => setStep(1), 3000);
      return () => clearTimeout(timer);
    } else if (step === 1) {
      // Simulate transcript processing
      const timer = setTimeout(() => setStep(2), transcript.length * 50 + 1500);
      return () => clearTimeout(timer);
    }
  }, [step, transcript.length]);

  return (
    <div className="simulation-container">
      <h3 className="simulation-title">Gemini Automating Meeting Notes:</h3>
      <AnimatePresence mode="wait">
        {step === 0 && (
          <motion.div
            key="zoom-sim"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.5 }}
            className="zoom-simulation-block"
          >
            <h4 className="zoom-title">Simulating Zoom Cloud Recordings...</h4>
            <div className="zoom-content">
              <p>Meeting: Weekly Sync - Project Alpha & Beta</p>
              <p>Date: March 7, 2026</p>
              <div className="zoom-action-bar">
                <span>Transcript.vtt</span>
                <motion.button
                  className="zoom-download-btn"
                  initial={{ x: 0 }}
                  animate={{ x: [0, 5, -5, 5, -5, 0] }}
                  transition={{ repeat: Infinity, duration: 1.5, ease: "easeInOut" }}
                >
                  Download Transcript
                </motion.button>
              </div>
            </div>
          </motion.div>
        )}

        {step === 1 && (
          <motion.div
            key="transcript-block"
            className="transcript-block"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.5, delayChildren: 0.5 }}
          >
            <motion.h4 variants={itemVariants} className="transcript-block-title">Raw Meeting Transcript:</motion.h4>
            {transcript.map((line, index) => (
              <motion.p key={`transcript-${index}`} variants={itemVariants} className="transcript-line">
                {line}
              </motion.p>
            ))}
          </motion.div>
        )}

        {step === 2 && (
          <motion.div
            key="summary-block"
            className="summary-block"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.5, delayChildren: 0.5 }}
          >
            <motion.h4 variants={itemVariants} className="summary-title">Generated by Gemini:</motion.h4>
            {summary.map((line, index) => (
              <motion.p key={`summary-${index}`} variants={itemVariants} className="summary-line">
                {line}
              </motion.p>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      <style jsx>{`
        .simulation-container {
          background-color: #fce4ec; /* Light pink background */
          border-radius: 12px;
          padding: 40px;
          margin: 40px auto;
          max-width: 900px;
          box-shadow: 0 8px 30px rgba(173, 20, 87, 0.2); /* Pinkish shadow */
          display: flex;
          flex-direction: column;
          gap: 25px;
        }
        .simulation-title {
          color: #880e4f; /* Darker pink/purple */
          font-family: 'Montserrat', sans-serif;
          text-align: center;
          margin-bottom: 30px;
          font-size: 2.2rem;
          font-weight: 800;
          text-shadow: 1px 1px 2px rgba(0,0,0,0.1);
        }

        .zoom-simulation-block {
          background-color: #f3e5f5; /* Lighter purple */
          border: 2px solid #ce93d8; /* Medium purple border */
          border-radius: 8px;
          padding: 25px;
          box-shadow: 0 4px 15px rgba(186, 104, 200, 0.2);
          text-align: center;
        }

        .zoom-title {
          color: #6a1b9a; /* Dark purple */
          font-size: 1.6rem;
          font-weight: 700;
          margin-bottom: 20px;
        }

        .zoom-content {
          background-color: #e1bee7; /* Even lighter purple */
          padding: 20px;
          border-radius: 6px;
          display: flex;
          flex-direction: column;
          gap: 10px;
        }

        .zoom-content p {
          margin: 0;
          color: #4a148c; /* Very dark purple */
          font-size: 1.1rem;
        }

        .zoom-action-bar {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 20px;
          padding-top: 15px;
          border-top: 1px dashed #ab47bc; /* Dashed purple line */
        }

        .zoom-action-bar span {
          font-weight: 600;
          color: #4a148c;
          font-size: 1rem;
        }

        .zoom-download-btn {
          background-color: #9c27b0; /* Bright purple */
          color: white;
          border: none;
          padding: 10px 20px;
          border-radius: 5px;
          font-size: 1rem;
          cursor: pointer;
          font-weight: 600;
          box-shadow: 0 2px 8px rgba(156, 39, 176, 0.3);
          transition: background-color 0.3s ease;
        }

        .zoom-download-btn:hover {
          background-color: #7b1fa2; /* Darker purple on hover */
        }

        .transcript-block,
        .summary-block {
          border: 2px solid #e0b4e0; /* Light pink/purple border */
          border-radius: 8px;
          padding: 20px;
          background-color: #fcecfc; /* Very light pink */
          box-shadow: inset 0 2px 5px rgba(216, 27, 96, 0.1);
        }

        .transcript-block-title {
          color: #ad1457; /* Deep pink */
          font-size: 1.5rem;
          font-weight: 700;
          margin-bottom: 15px;
        }

        .transcript-line {
          font-family: 'IBM Plex Mono', monospace;
          font-size: 1rem; /* Slightly larger */
          line-height: 1.8;
          color: #5d0f3a; /* Darker pink for text */
          margin: 0;
        }
        .summary-title {
          color: #d81b60; /* Vibrant pink */
          font-size: 1.8rem; /* Larger */
          font-weight: 700;
          margin-bottom: 15px;
        }
        .summary-line {
          font-family: 'Open Sans', sans-serif;
          font-size: 1.1rem; /* Slightly larger */
          line-height: 1.8;
          color: #880e4f; /* Darker pink/purple for text */
          margin: 0;
        }
        .card {
          margin: 1rem;
          flex-basis: 45%;
          padding: 1.5rem;
          text-align: left;
          color: inherit;
          text-decoration: none;
          border: 1px solid #ce93d8; /* Purple border for cards */
          border-radius: 10px;
          transition: color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease;
          background-color: #f3e5f5; /* Light purple card background */
        }

        .card:hover,
        .card:focus,
        .card:active {
          color: #880e4f; /* Darker pink/purple on hover */
          border-color: #880e4f; /* Darker pink/purple border on hover */
          background-color: #e1bee7; /* Slightly darker purple on hover */
        }

        .card h3 {
          margin: 0 0 1rem 0;
          font-size: 1.8rem; /* Larger font for card titles */
          color: #6a1b9a; /* Dark purple for card titles */
        }

        .card p,
        .card ul {
          margin: 0;
          font-size: 1.15rem; /* Slightly larger font for card text */
          line-height: 1.6;
          color: #4a148c; /* Dark purple for card text */
        }

        .card code {
          background: #e1bee7; /* Purple for code blocks */
          color: #4a148c; /* Dark purple for code text */
          border-radius: 5px;
          padding: 0.75rem;
          font-size: 1rem;
          font-family: 'IBM Plex Mono', monospace;
        }

        .title {
          color: #880e4f; /* Darker pink/purple for main title */
          font-size: 4.5rem;
        }

        .description {
          color: #ad1457; /* Deep pink for description */
          font-size: 1.6rem;
        }

        ul {
          list-style-type: disc;
          padding-left: 20px;
        }

        li {
          margin-bottom: 5px;
        }

        @media (max-width: 600px) {
          .grid {
            width: 100%;
            flex-direction: column;
          }
          .title {
            font-size: 3rem;
          }
          .description {
            font-size: 1.2rem;
          }
          .simulation-title {
            font-size: 1.8rem;
          }
          .zoom-title {
            font-size: 1.3rem;
          }
          .card h3 {
            font-size: 1.5rem;
          }
          .card p, .card ul {
            font-size: 1rem;
          }
        }
      `}</style>
    </div>
  );
};

export default function MeetingNotes() {
  return (
    <div className="container">
      <Head>
        <title>Automate Your Meeting Notes Forever</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">
          Automate Your Meeting Notes Forever
        </h1>

        <p className="description">
          Never dread taking meeting notes again! Gemini can transform raw transcripts into actionable insights, summaries, and email drafts in seconds.
        </p>

        <MeetingNotesSimulation />

        <div className="grid">
          <div className="card">
            <h3>Step 1: Get Your Transcript &rarr;</h3>
            <p>Use a tool like Otter.ai, Zoom's transcription, or Google Meet captions to get a text transcript of your meeting.</p>
            <code>"[00:00:05] John: Welcome everyone to the Q3 planning meeting... [00:00:15] Sarah: I've reviewed the latest sales figures..."</code>
          </div>

          <div className="card">
            <h3>Step 2: Paste into Gemini & Prompt &rarr;</h3>
            <p>Paste the full transcript into Gemini and ask for specific outputs.</p>
            <code>"Here is a meeting transcript. Please provide:
- A concise summary of key decisions.
- A list of action items with owners and deadlines.
- A draft email to attendees summarizing the meeting."</code>
          </div>

          <div className="card">
            <h3>Step 3: Refine & Customize &rarr;</h3>
            <p>Ask Gemini to adjust the output to fit your needs, e.g., change tone, add details, or focus on specific topics.</p>
            <code>"Make the email draft more formal and highlight the next steps for the marketing team."</code>
          </div>

          <div className="card">
            <h3>Example Output: Action Items &rarr;</h3>
            <ul>
              <li>**John:** Follow up with sales team on Q3 targets by EOD Friday.</li>
              <li>**Sarah:** Prepare a presentation on Q4 marketing strategy by next Monday.</li>
              <li>**Mike:** Research competitor analysis tools by Wednesday.</li>
            </ul>
          </div>

          <div className="card">
            <h3>Example Output: Meeting Summary &rarr;</h3>
            <p>The Q3 planning meeting focused on reviewing sales figures, discussing Q4 marketing strategies, and assigning action items for upcoming initiatives. Key decisions included prioritizing lead generation and exploring new market segments.</p>
          </div>
        </div>
      </main>

      <style jsx>{`
        .container {
          min-height: 100vh;
          padding: 0 0.5rem;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          background-color: #f8f0fc; /* Ensure consistency */
          color: #4a148c; /* Very dark purple text */
        }

        main {
          padding: 5rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        .title a {
          color: #9c27b0; /* Bright purple */
          text-decoration: none;
        }

        .title a:hover,
        .title a:focus,
        .title a:active {
          text-decoration: underline;
        }

        .title {
          margin: 0;
          line-height: 1.15;
          font-size: 4rem;
          text-align: center;
          color: #880e4f; /* Darker pink/purple for main title */
        }

        .description {
          line-height: 1.5;
          font-size: 1.5rem;
          text-align: center;
          color: #ad1457; /* Deep pink for description */
        }

        code {
          background: #e1bee7; /* Purple for code blocks */
          border-radius: 5px;
          padding: 0.75rem;
          font-size: 1.1rem;
          font-family: Menlo, Monaco, Lucida Console, Liberation Mono,
            DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace;
          color: #4a148c; /* Dark purple for code text */
          border: 1px solid #ce93d8; /* Purple border */
        }

        .grid {
          display: flex;
          align-items: center;
          justify-content: center;
          flex-wrap: wrap;
          max-width: 800px;
          margin-top: 3rem;
        }

        .card {
          margin: 1rem;
          flex-basis: 45%;
          padding: 1.5rem;
          text-align: left;
          color: #4a148c; /* Dark purple card text */
          text-decoration: none;
          border: 1px solid #ce93d8; /* Purple border for cards */
          border-radius: 10px;
          transition: color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease;
          background-color: #f3e5f5; /* Light purple card background */
          box-shadow: 0 4px 15px rgba(186, 104, 200, 0.2);
        }

        .card:hover,
        .card:focus,
        .card:active {
          color: #880e4f; /* Darker pink/purple on hover */
          border-color: #880e4f; /* Darker pink/purple border on hover */
          background-color: #e1bee7; /* Slightly darker purple on hover */
          box-shadow: 0 6px 20px rgba(186, 104, 200, 0.4);
        }

        .card h3 {
          margin: 0 0 1rem 0;
          font-size: 1.5rem;
          color: #6a1b9a; /* Dark purple for card titles */
        }

        .card p,
        .card ul {
          margin: 0;
          font-size: 1.25rem;
          line-height: 1.5;
          color: #4a148c; /* Dark purple for card text */
        }

        @media (max-width: 600px) {
          .grid {
            width: 100%;
            flex-direction: column;
          }
        }
      `}</style>

      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          background-color: #f8f0fc; /* Very light purple background */
          color: #4a148c; /* Very dark purple text */
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
            Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
            sans-serif;
        }

        a {
          color: #9c27b0; /* Bright purple links */
          text-decoration: none;
        }

        a:hover {
          text-decoration: underline;
        }

        * {
          box-sizing: border-box;
        }
      `}</style>
    </div>
  );
}
